# Generated by Django 3.1.4 on 2020-12-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoetype',
            name='style',
            field=models.CharField(choices=[('S', 'Sneaker'), ('B', 'Boot'), ('SA', 'Sandal'), ('D', 'Dress'), ('O', 'Other')], default='S', max_length=2),
        ),
    ]
